#sdk: "/home/prabhat/.rvm/gems/ruby-1.8.7-p352/gems/rhodes-3.2.3"
sdkversion: 3.2.1
name: my_lyric_app
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.mylyricapp
  BundleURLScheme: mylyricapp
wp:
  productid: 'df16d7c0-02e1-012f-b788-782bcbb1b5f7'
symbian:
  uid: '0xe539e0c7'
android:
  version: 2.1

extensions: ["json", "rexml", "set"]
