--- 
bbver: 4.6
sdk: /var/lib/gems/1.8/gems/rhodes-3.3.1
vendor: rhomobile
sdkversion: 2.0.0
applog: rholog.txt
iphone: 
  codesignidentity: 
  sdk: iphonesimulator3.0
  entitlements: 
  provisionprofile: 
  configuration: Debug
build: debug
android: 
  version: 2.1
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
capabilities: 
- pim
- vibrate
- phone
- gps
name: pimalerts
version: 1.0
extensions: 
- extension-name-here
- second-extension-name
